### ISSUE TITLE
about sentence embedding

### ISSUE THREAD

**Issue by thematrixduo** [antoine77340/MIL-NCE_HowTo100M#5]
Hi! just want to ask a quick question about sentence embedding. In this work the sentence embedding is just 2 fc with a max-pooling. I am wondering if you have experimented with more complex sentence embeddings, such as BERT? Is the current design to save computation costs, or does it work better than more complex models? Thanks!

**Comment by antoine77340** [comment]
Hi,

The two points you suggested are correct: it adds a lot of complexity to the overall model and does not seems to improve upon this simple "bag of word" neural network. We believe this is due to the fact that the text data is very noisy on HowTo, but that might need a more thorough investigation.

**Comment by thematrixduo** [comment]
I see, thanks!
